# Generated by Django 3.1.1 on 2020-10-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201006_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category_color_code',
            field=models.CharField(default='#a43b43', max_length=7),
        ),
    ]
