# Generated by Django 3.1.1 on 2020-10-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201006_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category_color_code',
        ),
        migrations.AddField(
            model_name='post',
            name='category_color_code_or_color_name',
            field=models.CharField(default='Example - #000000 or Blue', max_length=7),
        ),
    ]
