# Generated by Django 3.1.2 on 2020-10-22 12:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_profile'),
        ('blog', '0008_blogcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='user_image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.profile'),
            preserve_default=False,
        ),
    ]
