# Generated by Django 3.1.2 on 2020-10-23 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201022_1232'),
        ('blog', '0010_remove_blogcomment_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='user_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.profile'),
        ),
    ]
