# Generated by Django 3.1.2 on 2020-10-23 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_blogcomment_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='user_image',
        ),
    ]
