# Generated by Django 3.1.2 on 2020-10-27 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_blogcomment_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category_color_code_or_color_name',
        ),
    ]
