# Generated by Django 3.1.2 on 2020-10-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20201029_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail_image',
            field=models.ImageField(blank=True, default='/noimage.svg', upload_to='blog'),
        ),
    ]
