# Generated by Django 3.1.2 on 2020-10-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20201029_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail_image',
            field=models.ImageField(blank=True, default='/media/noimage.svg', upload_to='blog'),
        ),
    ]
