# Generated by Django 3.1.2 on 2020-10-23 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_blogcomment_user_image'),
        ('home', '0003_auto_20201022_1232'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
